version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2g

  crawler:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GH_PAT=${GH_PAT}
    command: [ "sh", "./wait-for-it.sh" ]
