# docker-compose.yml
version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  crawler:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - OPENAI_API_KEY=${OPENAI_API_KEY}
