services:
  - type: web
    name: movie-recommendation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=src uvicorn src.server:app --host 0.0.0.0 --port $PORT"
    staticPublishPath: "src/db"